#!/bin/bash
# VERSION 1.0
# Auteur : association ACIAH
# Licence : GPL - v3
# Modifications :
# Nom : aller-au-menu-fichier
# DESCRIPTION : la touche F1 pour accéder au menu Fichier
# DEPENDANCES : le script nécessite le paquet xdotool
# COMPLEMENTS :  
# RACCOURCIS : ce script est placé dans le dossier /usr/local/bin
# 
sleep 0.5 && xdotool key Alt+f
exit 0
